stages:
  - build
  - test
  - deploy

build:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-python-app .
    - docker push my-python-app

test:
  image: my-python-app
  script:
    - python test.py

deploy:
  image: docker
  script:
    - docker pull patient-app
    - docker run -d patient-app