name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set-branch-protection:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set branch protection rules
        run: |
          curl -X PUT -H "Accept: application/vnd.github.luke-cage-preview+json" \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": []
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 2
            },
            "restrictions": null,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'